from data.creature_banks import Creature_Bank, Crypt,Cyclops_Stockpile,Derelict_Ship,Dragon_Fly_Hive,Dragon_Utopia,Dwarven_Treasury,Griffin_Conservatory,\
Imp_Cache,Medusa_Stores,Naga_Bank,Shipwreck,Beholders_Sanctuary,Black_Tower,Churchyard,Experimental_Shop,Ivory_Tower,Mansion,Pirate_Cavern,\
Red_Tower,Ruins,Spit,Temple_of_the_Sea,Wolf_Raider_Picket

from data.objects_on_map import Mine,Sawmill,Ore_Pit,Crystal_Cavern,Gem_Pond,Alchemists_Lab,Sulfur_Dune,Gold_Mine,Abandoned_Mine,Arena,\
Colosseum_of_the_Magi,Garden_of_Revelation,Library_of_Enlightenment,Marletto_Tower,Mercenary_Camp,School_of_Magic,School_of_War,Star_Axis,\
Derrick,Lean_To,Mystical_Garden,Prospector,Warehouse_of_Crystal,Warehouse_of_Gem,Warehouse_of_Gold,Warehouse_of_Mercury,Warehouse_of_Ore,\
Warehouse_of_Sulfur,Warehouse_of_Wood,Water_Wheel,Windmill,Faerie_Ring,Fountain_of_Fortune,Idol_of_Fortune,Mermaids,Swan_Pond,Temple,Rally_Flag,\
Watering_Hole,Watering_Place,Fountain_of_Youth,Oasis,Stables,Campfire,Flotsam,Grave,Jetsam,Ocean_Bottle,Prison,Pandoras_Box,Scholar,Sea_Barrel,\
Sea_Chest,Shipwreck_Survivor,Treasure_Chest,Vial_Of_Mana,Wagon,Altar_of_Mana,Altar_of_Sacrifice,Ancient_Lamp,Anti_Magic_Garrison,Black_Market,\
Boat,Border_Gate,Border_Guard,Buoy,Cannon_Yard,Cartographer,Corpse,Cover_of_Darkness,Den_of_Thieves,Freelancers_Guild,Gazebo,Hermits_Shack,\
Hill_Fort,Hut_of_The_Magi,Junkman,Keymasters_Tent,Learning_Stone,Lighthouse,Magic_Spring,Magic_Well,Mineral_Spring,Monolith_One_Way_Entrance,\
Monolith_One_Way_Exit,Monolith_Two_Way,Obelisk,Observation_Tower,Observatory,Pillar_of_Fire,Portal_One_Way_Entrance,Portal_One_Way_Exit,\
Portal_Two_Way,Quest_Guard,Redwood_Observatory,Refugee_Camp,Sanctuary,Seafaring_Academy,Seers_Hut,Shipyard,Shrine_Of_Magic_Incantation,\
Shrine_Of_Magic_Gesture,Shrine_Of_Magic_Mystery,Shrine_Of_Magic_Thought,Subterranean_Gate,Temple_Of_Loyalty,Town_Gate,Trailblazer,Trading_Post,\
Tree_Of_Knowledge,Warlocks_Lab,Whirlpool,Witch_Hut,War_Machine_Factory,Garrison

from data.resources import Gold, Wood, Ore, Mercury, Sulfur, Crystal, Gems

# We will probably have to test this dict on every map and adjust our numbers accordingly

map_dict={
#castles
'Any':5,
'Castle':5,
'Rampart':5,
'Tower':5,
'Inferno':5,
'Necropolis':5,
'Dungeon':5,
'Stronghold':5,
'Fortress':5,
'Conflux':5,
'Neutral/Cove':5,

#misc
'Free':1,
'Possible':1,
'Blocked':0,
'Used':0,
'?':0,
'0':0,

#ground
'Dirt':2,
'Sand':2,
'Grass':1,
'Snow':1,
'Swamp':2,
'Rough':2,
'Subterranean':2,
'Lava':0,
'Water':0,
'Rock':0,
'Highlands':1,
'Wasteland':1,

#road
'None':2,
'Dirt road':2,
'Gravel road':2,
'Cobblestone road':2,

#monsters
'Pikeman':6,
'Halberdier':6,
'Archer':6,
'Marksman':6,
'Griffin':6,
'Royal Griffin':6,
'Swordsman':6,
'Crusader':6,
'Monk':6,
'Zealot':6,
'Cavalier':6,
'Champion':6,
'Angel':6,
'Archangel':6,
'Centaur':6,
'Centaur Captain':6,
'Dwarf':6,
'Battle Dwarf':6,
'Wood Elf':6,
'Grand Elf':6,
'Pegasus':6,
'Silver Pegasus':6,
'Dendroid Guard':6,
'Dendroid Soldier':6,
'Unicorn':6,
'War Unicorn':6,
'Green Dragon':6,
'Gold Dragon':6,
'Gremlin':6,
'Master Gremlin':6,
'Stone Gargoyle':6,
'Obsidian Gargoyle':6,
'Stone Golem':6,
'Iron Golem':6,
'Mage':6,
'Arch Mage':6,
'Genie':6,
'Master Genie':6,
'Naga':6,
'Naga Queen':6,
'Giant':6,
'Titan':6,
'Imp':6,
'Familiar':6,
'Gog':6,
'Magog':6,
'Hell Hound':6,
'Cerberus':6,
'Demon':6,
'Horned Demon':6,
'Pit Fiend':6,
'Pit Lord':6,
'Efreeti':6,
'Efreet Sultan':6,
'Devil':6,
'Arch Devil':6,
'Skeleton':6,
'Skeleton Warrior':6,
'Walking Dead':6,
'Zombie':6,
'Wight':6,
'Wraith':6,
'Vampire':6,
'Vampire Lord':6,
'Lich':6,
'Power Lich':6,
'Black Knight':6,
'Dread Knight':6,
'Bone Dragon':6,
'Ghost Dragon':6,
'Troglodyte':6,
'Infernal Troglodyte':6,
'Harpy':6,
'Harpy Hag':6,
'Beholder':6,
'Evil Eye':6,
'Medusa':6,
'Medusa Queen':6,
'Minotaur':6,
'Minotaur King':6,
'Manticore':6,
'Scorpicore':6,
'Red Dragon':6,
'Black Dragon':6,
'Goblin':6,
'Hobgoblin':6,
'Wolf Rider':6,
'Wolf Raider':6,
'Orc':6,
'Orc Chieftain':6,
'Ogre':6,
'Ogre Mage':6,
'Roc':6,
'Thunderbird':6,
'Cyclops':6,
'Cyclops King':6,
'Behemoth':6,
'Ancient Behemoth':6,
'Gnoll':6,
'Gnoll Marauder':6,
'Lizardman':6,
'Lizard Warrior':6,
'Gorgon':6,
'Mighty Gorgon':6,
'Serpent Fly':6,
'Dragon Fly':6,
'Basilisk':6,
'Greater Basilisk':6,
'Wyvern':6,
'Wyvern Monarch':6,
'Hydra':6,
'Chaos Hydra':6,
'Air Elemental':6,
'Earth Elemental':6,
'Fire Elemental':6,
'Water Elemental':6,
'Gold Golem':6,
'Diamond Golem':6,
'Pixie':6,
'Sprite':6,
'Psychic Elemental':6,
'Magic Elemental':6,
'NOT USED (attacker)':0,   # moze zamiast obstacle 0 dac dirt 1?
'Ice Elemental':6,
'NOT USED (defender)':0,   # moze zamiast obstacle 0 dac dirt 1?
'Magma Elemental':6,
'NOT USED (3)':0,   # moze zamiast obstacle 0 dac dirt 1?
'Storm Elemental':6,
'NOT USED (4)':0,   # moze zamiast obstacle 0 dac dirt 1?
'Energy Elemental':6,
'Firebird':6,
'Phoenix':6,
'Azure Dragon':6,
'Crystal Dragon':6,
'Faerie Dragon':6,
'Rust Dragon':6,
'Enchanter':6,
'Sharpshooter':6,
'Halfling':6,
'Peasant':6,
'Boar':6,
'Mummy':6,
'Nomad':6,
'Rogue':6,
'Troll':6,
'Catapult (specialty X1)':6, # potencjalne problemy?
'Ballista (specialty X1)':6, # potencjalne problemy?
'First Aid Tent (specialty X1)':6, # potencjalne problemy?
'Ammo Cart (specialty X1)':6, # potencjalne problemy?
'Arrow Towers (specialty X1)':6, # potencjalne problemy?

# HOTA
'Sea Dog':6,
'Nymph':6,
'Oceanid':6,
'Crew Mate':6,
'Seaman':6,
'Pirate':6,
'Corsair':6,
'Stormbird':6,
'Ayssid':6,
'Sea Witch':6,
'Sorceress':6,
'Nix':6,
'Nix Warrior':6,
'Sea Serpent':6,
'Haspid':6,
'Leprechaun':6,
'Satyr':6,
'Steel Golem':6,
'Fangarm':6,
'Random':6,
'Supreme Archangel':6,
'Diamond Dragon':6,
'Lord of Thunder':6,
'Antichrist':6,
'Blood Dragon':6,
'Darkness Dragon':6,
'Ghost Behemoth':6,
'Hell Hydra':6,
'Sacred Phoenix':6,
'Ghost':6,
'Emissary of War':6,
'Emissary of Peace':6,
'Emissary of Mana':6,
'Emissary of Lore':6,
'Fire Messenger':6,
'Earth Messenger':6,
'Air Messenger':6,
'Water Messenger':6,
'Gorynych':6,
'War zealot':6,
'Arctic Sharpshooter':6,
'Lava Sharpshooter':6,
'Nightmare':6,
'Santa Gremlin':6,
'Paladin (attacker)':6,
'Hierophant (attacker)':6,
'Temple Guardian (attacker)':6,
'Succubus (attacker)':6,
'Soul Eater (attacker)':6,
'Brute (attacker)':6,
'Ogre Leader (attacker)':6,
'Shaman (attacker)':6,
'Astral Spirit (attacker)':6,
'Paladin (defender)':6,
'Hierophant (defender)':6,
'Temple Guardian (defender)':6,
'Succubus (defender)':6,
'Soul Eater (defender)':6,
'Brute (defender)':6,
'Ogre Leader (defender)':6,
'Shaman (defender)':6,
'Astral Spirit (defender)':6,
'Sylvan Centaur':6,
'Werewolf':6,
'Hell Steed':6,
'Dracolich':6,
'Random lvl 1':6,
'Random lvl 1 Upg':6,
'Random lvl 2':6,
'Random lvl 2 Upg':6,
'Random lvl 3':6,
'Random lvl 3 Upg':6,
'Random lvl 4':6,
'Random lvl 4 Upg':6,
'Random lvl 5':6,
'Random lvl 5 Upg':6,
'Random lvl 6':6,
'Random lvl 6 Upg':6,
'Random lvl 7':6,
'Random lvl 7 Upg':6,

#objects
'Altar of Sacrifice':Altar_of_Sacrifice,
'Anchor Point':0, # nie mamy tego
'Arena':Arena,
'Artifact':7,
'Pandoras Box':Pandoras_Box, # chyba nie mamy obslugi tego
'Black Market':Black_Market, # chyba nie mamy obslugi tego
'Boat':Boat, # chyba nie mamy obslugi tego
'Borderguard':Border_Guard, # chyba nie mamy obslugi tego
'Keymasters Tent':Keymasters_Tent, # chyba nie mamy obslugi tego
'Buoy':Buoy,
'Campfire':Campfire,
'Cartographer':Cartographer,
'Swan Pond':Swan_Pond,
'Cover of Darkness':Cover_of_Darkness,
'Creature Bank':9,
'Creature Generator 1':9,
'Creature Generator 2':9,
'Creature Generator 3':9,
'Creature Generator 4':9,
'Cursed Ground':2,
'Corpse':Corpse,
'Marletto Tower':Marletto_Tower,
'Derelict Ship':Derelict_Ship,
'Dragon Utopia':Dragon_Utopia,
'Event':0,
'Eye of the Magi':0, # nie mamy tego
'Faerie Ring':Faerie_Ring,
'Flotsam':Flotsam,
'Fountain of Fortune':Fountain_of_Fortune,
'Fountain of Youth':Fountain_of_Youth,
'Garden of Revelation':Garden_of_Revelation,
'Garrison':Garrison,
'Hero':0,
'Hill Fort':Hill_Fort,
'Grail':0,
'Hut of the Magi':Hut_of_The_Magi,
'Idol of Fortune':Idol_of_Fortune,
'Lean To':Lean_To,
'<blank>':0, # lub dirt 1?
'Library of Enlightenment':Library_of_Enlightenment,
'Lighthouse':Lighthouse,
'Monolith One Way Entrance':Monolith_One_Way_Entrance,
'Monolith One Way Exit':Monolith_One_Way_Exit,
'Monolith Two Way':Monolith_Two_Way,
'Magic Plains':1,
'School of Magic':School_of_Magic,
'Magic Spring':Magic_Spring,
'Magic Well':Magic_Well,
'Mercenary Camp':Mercenary_Camp,
'Mermaid':Mermaids,
'Mine':Mine,
'Monster':6,
'Mystical Garden':Mystical_Garden,
'Oasis':Oasis,
'Obelisk':Obelisk,
'Redwood Observatory':Redwood_Observatory,
'Ocean Bottle':Ocean_Bottle,
'Pillar of Fire':Pillar_of_Fire,
'Star Axis':Star_Axis,
'Prison':Prison,
'Pyramid':0, #brak klasy
'Rally Flag':Rally_Flag,
'Random Artifact':7,
'Random Treasure Artifact':7,
'Random Minor Artifact':7,
'Random Major Artifact':7,
'Random Relic':7,
'Random Hero':1,
'Random Monster':6,
'Random Monster 1':6,
'Random Monster 2':6,
'Random Monster 3':6,
'Random Monster 4':6,
'Random Resource':3,
'Random Town':5,
'Refugee Camp':Refugee_Camp,
'Resource':3,
'Sanctuary':Sanctuary,
'Scholar':Scholar,
'Sea Chest':Sea_Chest,
'Seers Hut':Seers_Hut,
'Crypt':Crypt,
'Shipwreck':Shipwreck,
'Shipwreck Survivor':Shipwreck_Survivor,
'Shipyard':Shipyard,
'Shrine of Magic Incantation':Shrine_Of_Magic_Incantation,
'Shrine of Magic Gesture':Shrine_Of_Magic_Gesture,
'Shrine of Magic Thought':Shrine_Of_Magic_Thought,
'Sign':0,
'Sirens':0,
'Stables':Stables,
'Tavern':0, # chcemy to czytac z mapy? mamy obsluge tego na mapie?
'Temple':Temple,
'Den of Thieves':Den_of_Thieves,
'Town':5,
'Trading Post':Trading_Post,
'Learning Stone':Learning_Stone,
'Treasure Chest': 8,
'Tree of Knowledge':Tree_Of_Knowledge,
'Subterranean Gate':Subterranean_Gate,
'University':0,
'Wagon':Wagon,
'War Machine Factory':War_Machine_Factory,
'School of War':School_of_War,
'Warriors Tomb':0,
'Water Wheel':Water_Wheel,
'Watering Hole':Watering_Hole,
'Whirlpool':Whirlpool,
'Windmill':Windmill,
'Witch Hut':Witch_Hut,
'Brush':0,
'Bush':0,
'Cactus':0,
'Canyon':0,
'Crater':0,
'Dead Vegetation':0,
'Flowers':1,
'Frozen Lake':0,
'Hedge':0,
'Hill':0,
'Hole':0,
'Kelp':0,
'Lake':0,
'Lava Flow':0,
'Lava Lake':0,
'Mushrooms':0,
'Log':0,
'Mandrake':0,
'Moss':1,
'Mound':0,
'Mountain':0,
'Oak Trees':0,
'Outcropping':0,
'Pine Trees':0,
'Plant':0,
'River Delta':0,
'Sand Dune':0,
'Sand Pit':0,
'Shrub':0,
'Skull':0,
'Stalagmite':0,
'Stump':0,
'Tar Pit':0,
'Trees':0,
'Vine':0,
'Volcanic Vent':0,
'Volcano':0,
'Willow Trees':0,
'Yucca Trees':0,
'Reef':0,
'Random Monster 5':6,
'Random Monster 6':6,
'Random Monster 7':6,
'Desert Hills':0,
'Dirt Hills':0,
'Grass Hills':0,
'Rough Hills':0,
'Subterranean Rocks':0,
'Swamp Foliage':0,
'Border Gate':Border_Gate,
'Freelancers Guild':Freelancers_Guild,
'Hero Placeholder':1,
'Quest Guard':Quest_Guard,
'Random Dwelling':4,
'Random dwelling with no home castle type':4,
'Random dwelling with home castle type':4,
'Abandoned Mine':Abandoned_Mine,

#magical terrain
'Clover Field':1,
'Evil Fog':1,
'Favourable Winds':1,
'Fiery Fields':1,
'Holy Ground':1,
'Lucid Pools':1,
'Magic Clouds':1,
'Rocklands':1,
'Sawmill':Sawmill,
'Alchemists Lab':Alchemists_Lab,
'Ore Pit':Ore_Pit,
'Sulfur Dune':Sulfur_Dune,
'Crystal Cavern':Crystal_Cavern,
'Gem Pond':Gem_Pond,
'Gold Mine':Gold_Mine,

#resources
'Wood':3,
'Mercury':3,
'Ore':3,
'Sulfur':3,
'Crystal':3,
'Gems':3,
'Gold':3,
'Wood and Ore':3,
'Mercury, Sulfur, Crystal and Gems':3,

#artifacts
'Spell book':7,
'Spell Scroll':7,
'Catapult':7,
'Ballista':7,
'Ammo Cart':7,
'First Aid Tent':7,
'Centaur Axe':7,
'Blackshard of the Dead Knight':7,
'Greater Gnoll\'s Flail':7,
'Ogre\'s Club of Havoc':7,
'Sword of Hellfire':7,
'Titan\'s Gladius':7,
'Shield of the Dwarven Lords':7,
'Shield of the Yawning Dead':7,
'Buckler of the Gnoll King':7,
'Targ of the Rampaging Ogre':7,
'Shield of the Damned':7,
'Sentinel\'s Shield':7,
'Helm of the Alabaster Unicorn':7,
'Skull Helmet':7,
'Helm of Chaos':7,
'Crown of the Supreme Magi':7,
'Hellstorm Helmet':7,
'Thunder Helmet':7,
'Breastplate of Petrified Wood':7,
'Rib Cage':7,
'Scales of the Greater Basilisk':7,
'Tunic of the Cyclops King':7,
'Breastplate of Brimstone':7,
'Titan\'s Cuirass':7,
'Armor of Wonder':7,
'Sandals of the Saint':7,
'Celestial Necklace of Bliss':7,
'Lion\'s Shield of Courage':7,
'Sword of Judgement':7,
'Helm of Heavenly Enlightenment':7,
'Quiet Eye of the Dragon':7,
'Red Dragon Flame Tongue':7,
'Dragon Scale Shield':7,
'Dragon Scale Armor':7,
'Dragonbone Greaves':7,
'Dragon Wing Tabard':7,
'Necklace of Dragonteeth':7,
'Crown of Dragontooth':7,
'Still Eye of the Dragon':7,
'Clover of Fortune':7,
'Cards of Prophecy':7,
'Ladybird of Luck':7,
'Badge of Courage':7,
'Crest of Valor':7,
'Glyph of Gallantry':7,
'Speculum':7,
'Spyglass':7,
'Amulet of the Undertaker':7,
'Vampire\'s Cowl':7,
'Dead Man\'s Boots':7,
'Garniture of Interference':7,
'Surcoat of Counterpoise':7,
'Boots of Polarity':7,
'Bow of Elven Cherrywood':7,
'Bowstring of the Unicorn\'s Mane':7,
'Angel Feather Arrows':7,
'Bird of Perception':7,
'Stoic Watchman':7,
'Emblem of Cognizance':7,
'Statesman\'s Medal':7,
'Diplomat\'s Ring':7,
'Ambassador\'s Sash':7,
'Ring of the Wayfarer':7,
'Equestrian\'s Gloves':7,
'Necklace of Ocean Guidance':7,
'Angel Wings':7,
'Charm of Mana':7,
'Talisman of Mana':7,
'Mystic Orb of Mana':7,
'Collar of Conjuring':7,
'Ring of Conjuring':7,
'Cape of Conjuring':7,
'Orb of the Firmament':7,
'Orb of Silt':7,
'Orb of Tempestuous Fire':7,
'Orb of Driving Rain':7,
'Recanter\'s Cloak':7,
'Spirit of Oppression':7,
'Hourglass of the Evil Hour':7,
'Tome of Fire Magic':7,
'Tome of Air Magic':7,
'Tome of Water Magic':7,
'Tome of Earth Magic':7,
'Boots of Levitation':7,
'Golden Bow':7,
'Sphere of Permanence':7,
'Orb of Vulnerability':7,
'Ring of Vitality':7,
'Ring of Life':7,
'Vial of Lifeblood':7,
'Necklace of Swiftness':7,
'Boots of Speed':7,
'Cape of Velocity':7,
'Pendant of Dispassion':7,
'Pendant of Second Sight':7,
'Pendant of Holiness':7,
'Pendant of Life':7,
'Pendant of Death':7,
'Pendant of Free Will':7,
'Pendant of Negativity':7,
'Pendant of Total Recall':7,
'Pendant of Courage':7,
'Everflowing Crystal Cloak':7,
'Ring of Infinite Gems':7,
'Everpouring Vial of Mercury':7,
'Inexhaustible Cart of Ore':7,
'Eversmoking Ring of Sulfur':7,
'Inexhaustible Cart of Lumber':7,
'Endless Sack of Gold':7,
'Endless Bag of Gold':7,
'Endless Purse of Gold':7,
'Legs of Legion':7,
'Loins of Legion':7,
'Torso of Legion':7,
'Arms of Legion':7,
'Head of Legion':7,
'Sea Captain\'s Hat':7,
'Spellbinder\'s Hat':7,
'Shackles of War':7,
'Orb of Inhibition':7,
'Vial of Dragon Blood':7,
'Armageddon\'s Blade':7,
'Angelic Alliance':7,
'Cloak of the Undead King':7,
'Elixir of Life':7,
'Armor of the Damned':7,
'Statue of Legion':7,
'Power of the Dragon Father':7,
'Titan\'s Thunder':7,
'Admiral\'s Hat':7,
'Bow of the Sharpshooter':7,
'Wizard\'s Well':7,
'Ring of the Magi':7,
'Cornucopia':7,

# WOG
'Magic Wand *':7,
'Gold Tower Arrow *':7,
'Monster\'s Power *':7,
'Highlighted Slot **':7,
'Artifact Lock **':7,
'Axe of Smashing ***':7,
'Mithril Mail ***':7,
'Sword of Sharpness ***':7,
'Helm of Immortality ***':7,
'Pendant of Sorcery ***':7,
'Boots of Haste ***':7,
'Bow of Seeking ***':7,
'Dragon Eye Ring ***':7,
'Hardened Shield ***':7,
'Slava\'s Ring of Power ***':7,
'Warlord\'s banner *':7,
'Crimson Shield of Retribution *':7,
'Barbarian Lord\'s Axe of Ferocity *':7,
'Dragonheart *':7,
'Gate Key *':7,
'Blank Helmet ****':7,
'Blank Sword ****':7,
'Blank Shield ****':7,
'Blank Horned Ring ****':7,
'Blank Gemmed Ring ****':7,
'Blank Neck Broach ****':7,
'Blank Armor ****':7,
'Blank Surcoat ****':7,
'Blank Boots ****':7,
'Blank Horn ****':7,

#buildings
'Town hall':0,
'City hall':0,
'Capitol':0,
'Fort':0,
'Citadel':0,
'Blacksmith':0,
'Marketplace':0,
'Resource silo':0,
'Mages guild 1':0,
'Mages guild 2':0,
'Mages guild 3':0,
'Mages guild 4':0,
'Mages guild 5':0,
'Special 1':0,
'Special 2':0,
'Special 3':0,
'Special 4':0,
'Dwelling lvl 1':4,
'Dwelling lvl 1 upg':4,
'Horde lvl 1':6,
'Dwelling lvl 2':4,
'Dwelling lvl 2 upg':4,
'Horde lvl 2':6,
'Dwelling lvl 3':4,
'Dwelling lvl 3 upg':4,
'Horde lvl 3':6,
'Dwelling lvl 4':4,
'Dwelling lvl 4 upg':4,
'Horde lvl 4':6,
'Dwelling lvl 5':4,
'Dwelling lvl 5 upg':4,
'Horde lvl 5':6,
'Dwelling lvl 6':4,
'Dwelling lvl 6 upg':4,
'Dwelling lvl 7':4,
'Dwelling lvl 7 upg':4,

'Visible':0,
'Visitable':1,
'Combined':0,
}
