from PyQt5 import QtCore, QtGui, QtWidgets
import os

class AcousticWindow2(object):
    def setupUi(self, OpticTest2):
        OpticTest2.setObjectName("OpticTest2")
        OpticTest2.resize(586, 443)
        self.informacja = QtWidgets.QLabel(OpticTest2)
        self.informacja.setGeometry(QtCore.QRect(10, 10, 561, 361))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.informacja.setFont(font)
        self.informacja.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.informacja.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.informacja.setWordWrap(True)
        self.informacja.setObjectName("informacja")
        self.przycisk = QtWidgets.QPushButton(OpticTest2)
        self.przycisk.setGeometry(QtCore.QRect(260, 350, 311, 81))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.przycisk.setFont(font)
        self.przycisk.setAutoFillBackground(False)
        self.przycisk.setObjectName("przycisk")
        self.start = QtWidgets.QPushButton(OpticTest2)
        self.start.setEnabled(False)
        self.start.setGeometry(QtCore.QRect(10, 350, 271, 81))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.start.setFont(font)
        self.start.setAutoFillBackground(False)
        self.start.setObjectName("start")
        self.test = QtWidgets.QPushButton(OpticTest2)
        self.test.setEnabled(False)
        self.test.setGeometry(QtCore.QRect(300, 350, 271, 81))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.test.setFont(font)
        self.test.setAutoFillBackground(False)
        self.test.setObjectName("test")
        self.zwierzaczek1 = QtWidgets.QLabel(OpticTest2)
        self.zwierzaczek1.setGeometry(QtCore.QRect(15, 90, 161, 161))
        self.zwierzaczek1.setText("")
        self.zwierzaczek1.setObjectName("zwierzaczek1")
        self.typtestu = QtWidgets.QLabel(OpticTest2)
        self.typtestu.setEnabled(True)
        self.typtestu.setGeometry(QtCore.QRect(170, 10, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(False)
        font.setWeight(50)
        self.typtestu.setFont(font)
        self.typtestu.setAutoFillBackground(False)
        self.typtestu.setAlignment(QtCore.Qt.AlignCenter)
        self.typtestu.setObjectName("typtestu")
        self.szybkosc = QtWidgets.QLabel(OpticTest2)
        self.szybkosc.setGeometry(QtCore.QRect(140, 60, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.szybkosc.setFont(font)
        self.szybkosc.setAutoFillBackground(False)
        self.szybkosc.setText("")
        self.szybkosc.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.szybkosc.setObjectName("szybkosc")
        self.zwierzaczek2 = QtWidgets.QLabel(OpticTest2)
        self.zwierzaczek2.setGeometry(QtCore.QRect(220, 90, 161, 161))
        self.zwierzaczek2.setText("")
        self.zwierzaczek2.setObjectName("zwierzaczek2")
        self.zwierzaczek3 = QtWidgets.QLabel(OpticTest2)
        self.zwierzaczek3.setGeometry(QtCore.QRect(420, 90, 141, 161))
        self.zwierzaczek3.setText("")
        self.zwierzaczek3.setObjectName("zwierzaczek3")
        self.kon = QtWidgets.QPushButton(OpticTest2)
        self.kon.setEnabled(False)
        self.kon.setGeometry(QtCore.QRect(220, 280, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.kon.setFont(font)
        self.kon.setAutoFillBackground(False)
        self.kon.setObjectName("kon")
        self.malpa = QtWidgets.QPushButton(OpticTest2)
        self.malpa.setEnabled(False)
        self.malpa.setGeometry(QtCore.QRect(10, 280, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.malpa.setFont(font)
        self.malpa.setAutoFillBackground(False)
        self.malpa.setObjectName("malpa")
        self.lew = QtWidgets.QPushButton(OpticTest2)
        self.lew.setEnabled(False)
        self.lew.setGeometry(QtCore.QRect(410, 280, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lew.setFont(font)
        self.lew.setAutoFillBackground(False)
        self.lew.setObjectName("lew")

        self.lew.hide()
        self.malpa.hide()
        self.kon.hide()

        self.typtestu.hide()
        self.test.hide()
        self.start.hide()

        self.retranslateUi(OpticTest2)
        QtCore.QMetaObject.connectSlotsByName(OpticTest2)

    def retranslateUi(self, OpticTest2):
        _translate = QtCore.QCoreApplication.translate
        OpticTest2.setWindowTitle(_translate("OpticTest2", "Test Akustyczny Złożony"))
        self.informacja.setText(_translate("OpticTest2", "Test akustyczny złożony. Po kliknięciu 'Dalej' ukaże się okienko z badaniem. Domyślnie tryb badania ustawione jest na 'Szkolenie'. W celu przejścia do trybu 'Testu' należy kliknąć przycisk w prawym dolnym rogu. Podczas szkolenia wyniki nie będą zapisywane. W celu uruchomienia badania należy kliknąć 'Start'. Następnie należy poczekać aż miną 4 sygnały dźwiękowe, które oznaczają start badania. Badanie polega na odpowiedniej reakcji i rozpoznaniu dźwięku - małpy, konia lub lwa. Po rozpoznaniu dźwięku należy go odpowiednio zaznaczyć pod obrazkami zwierząt.  Czas reakcji jest mierzony i wyświetlany na ekranie. W celu zobaczenia wszystkich wyników należy przejść do głównego okienka aplikacji i kliknąć przycisk 'Wyświetl wyniki'."))
        self.przycisk.setText(_translate("OpticTest2", "Dalej"))
        self.start.setText(_translate("OpticTest2", "Start"))
        self.test.setText(_translate("OpticTest2", "Test"))
        self.typtestu.setText(_translate("OpticTest2", "Szkolenie"))
        self.kon.setText(_translate("OpticTest2", "Koń"))
        self.malpa.setText(_translate("OpticTest2", "Małpa"))
        self.lew.setText(_translate("OpticTest2", "Lew"))
        self.setWindowIcon(QtGui.QIcon(os.getcwd()+'/data/ucho.jpg'))
