from PyQt5 import QtCore, QtGui, QtWidgets
import os

class AcousticWindow(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(586, 443)
        self.informacja = QtWidgets.QLabel(Form)
        self.informacja.setGeometry(QtCore.QRect(10, 10, 561, 361))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.informacja.setFont(font)
        self.informacja.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.informacja.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.informacja.setWordWrap(True)
        self.informacja.setObjectName("informacja")
        self.przycisk = QtWidgets.QPushButton(Form)
        self.przycisk.setGeometry(QtCore.QRect(260, 350, 311, 81))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.przycisk.setFont(font)
        self.przycisk.setAutoFillBackground(False)
        self.przycisk.setObjectName("przycisk")
        self.start = QtWidgets.QPushButton(Form)
        self.start.setGeometry(QtCore.QRect(10, 350, 271, 81))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.start.setFont(font)
        self.start.setAutoFillBackground(False)
        self.start.setObjectName("start")
        self.test = QtWidgets.QPushButton(Form)
        self.test.setGeometry(QtCore.QRect(300, 350, 271, 81))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.test.setFont(font)
        self.test.setAutoFillBackground(False)
        self.test.setObjectName("test")
        self.reakcja = QtWidgets.QPushButton(Form)
        self.reakcja.setGeometry(QtCore.QRect(140, 260, 311, 81))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.reakcja.setFont(font)
        self.reakcja.setAutoFillBackground(False)
        self.reakcja.setObjectName("Reakcja")
        self.tlo = QtWidgets.QLabel(Form)
        self.tlo.setGeometry(QtCore.QRect(10, 70, 571, 181))
        self.tlo.setText("")
        self.tlo.setObjectName("tlo")
        self.typtestu = QtWidgets.QLabel(Form)
        self.typtestu.setGeometry(QtCore.QRect(170, 10, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(False)
        font.setWeight(50)
        self.typtestu.setFont(font)
        self.typtestu.setAutoFillBackground(False)
        self.typtestu.setText("")
        self.typtestu.setAlignment(QtCore.Qt.AlignCenter)
        self.typtestu.setObjectName("typtestu")

        self.odliczanie = QtWidgets.QLabel(Form)
        self.odliczanie.setGeometry(QtCore.QRect(170, 100, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(False)
        font.setWeight(50)
        self.odliczanie.setFont(font)
        self.odliczanie.setAutoFillBackground(False)
        self.odliczanie.setText("")
        self.odliczanie.setAlignment(QtCore.Qt.AlignCenter)
        self.odliczanie.setObjectName("odliczanie")

        self.szybkosc = QtWidgets.QLabel(Form)
        self.szybkosc.setGeometry(QtCore.QRect(460, 260, 111, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.szybkosc.setFont(font)
        self.szybkosc.setAutoFillBackground(False)
        self.szybkosc.setText("")
        self.szybkosc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.szybkosc.setObjectName("szybkosc")
        self.szybkosc.setWordWrap(True)

        self.reakcja.hide()
        self.start.hide()
        self.test.hide()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Test Akustyczny"))
        self.informacja.setText(_translate("Form", "Test akustyczny prosty. Po kliknięciu 'Dalej' ukaże się okienko z badaniem. Domyślnie tryb badania ustawione jest na 'Szkolenie'. W celu przejścia do trybu 'Testu' należy kliknąć przycisk w prawym dolnym rogu. Podczas szkolenia wyniki nie będą zapisywane. W celu uruchomienia badania należy kliknąć 'Start'. Następnie należy poczekać na sygnał 'Start!' na ekranie. Badanie polega na reakcji na dźwięk. Użytkownik wciela się w tłum w kawiarni, po usłyszeniu dźwięku tłuczonej szklanki należy wcisnąć przycisk 'Reakcja', żeby uruchomić reakcję tłumu. Czas reakcji jest mierzony i wyświetlany na ekranie. W celu zobaczenia wszystkich wyników należy przejść do głównego okienka aplikacji i kliknąć przycisk 'Wyświetl wyniki'."))
        self.przycisk.setText(_translate("Form", "Dalej"))
        self.start.setText(_translate("Form", "Start"))
        self.test.setText(_translate("Form", "Test"))
        self.reakcja.setText(_translate("Form", "Reakcja"))
        self.setWindowIcon(QtGui.QIcon(os.getcwd()+'/data/ucho.jpg'))

