from PyQt5 import QtCore, QtGui, QtWidgets
import os

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(493, 341)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.testOptyczny = QtWidgets.QPushButton(self.centralwidget)
        self.testOptyczny.setGeometry(QtCore.QRect(10, 80, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.testOptyczny.setFont(font)
        self.testOptyczny.setObjectName("testOptyczny")
        self.testAkustyczny = QtWidgets.QPushButton(self.centralwidget)
        self.testAkustyczny.setGeometry(QtCore.QRect(250, 80, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.testAkustyczny.setFont(font)
        self.testAkustyczny.setObjectName("testAkustyczny")
        self.wyswietlanieWynikow = QtWidgets.QPushButton(self.centralwidget)
        self.wyswietlanieWynikow.setGeometry(QtCore.QRect(20, 220, 451, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.wyswietlanieWynikow.setFont(font)
        self.wyswietlanieWynikow.setObjectName("wyswietlanieWynikow")
        self.informacjaTesty = QtWidgets.QLabel(self.centralwidget)
        self.informacjaTesty.setGeometry(QtCore.QRect(10, 10, 471, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.informacjaTesty.setFont(font)
        self.informacjaTesty.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.informacjaTesty.setAlignment(QtCore.Qt.AlignCenter)
        self.informacjaTesty.setWordWrap(True)
        self.informacjaTesty.setObjectName("informacjaTesty")
        self.testOptycznyAdv = QtWidgets.QPushButton(self.centralwidget)
        self.testOptycznyAdv.setGeometry(QtCore.QRect(10, 150, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.testOptycznyAdv.setFont(font)
        self.testOptycznyAdv.setObjectName("testOptycznyAdv")
        self.testAkustycznyAdv = QtWidgets.QPushButton(self.centralwidget)
        self.testAkustycznyAdv.setGeometry(QtCore.QRect(250, 150, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.testAkustycznyAdv.setFont(font)
        self.testAkustycznyAdv.setObjectName("testAkustycznyAdv")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 493, 26))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "ASK - laboratorium nr 3"))
        self.testOptyczny.setText(_translate("mainWindow", "Test Optyczny Prosty"))
        self.testAkustyczny.setText(_translate("mainWindow", "Test Akustyczny Prosty"))
        self.wyswietlanieWynikow.setText(_translate("mainWindow", "Wyświetl aktualne wyniki"))
        self.informacjaTesty.setText(_translate("mainWindow", "Program służy do badania sprawności psychomotorycznej. Proszę o wybranie typu testu w celu zbadania."))
        self.testOptycznyAdv.setText(_translate("mainWindow", "Test Optyczny Złożony"))
        self.testAkustycznyAdv.setText(_translate("mainWindow", "Test Akustyczny Złożony"))
        self.setWindowIcon(QtGui.QIcon(os.getcwd()+'/data/logo.jpg'))