from PyQt5 import QtCore, QtGui, QtWidgets
import os

class OpticWindow(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(586, 443)
        self.informacja = QtWidgets.QLabel(Form)
        self.informacja.setGeometry(QtCore.QRect(10, 10, 561, 361))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.informacja.setFont(font)
        self.informacja.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.informacja.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.informacja.setWordWrap(True)
        self.informacja.setObjectName("informacja")
        self.przycisk = QtWidgets.QPushButton(Form)
        self.przycisk.setGeometry(QtCore.QRect(260, 350, 311, 81))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.przycisk.setFont(font)
        self.przycisk.setAutoFillBackground(False)
        self.przycisk.setObjectName("przycisk")
        self.start = QtWidgets.QPushButton(Form)
        self.start.setGeometry(QtCore.QRect(10, 350, 271, 81))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.start.setFont(font)
        self.start.setAutoFillBackground(False)
        self.start.setObjectName("start")
        self.test = QtWidgets.QPushButton(Form)
        self.test.setGeometry(QtCore.QRect(300, 350, 271, 81))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.test.setFont(font)
        self.test.setAutoFillBackground(False)
        self.test.setObjectName("test")
        self.kolor = QtWidgets.QPushButton(Form)
        self.kolor.setGeometry(QtCore.QRect(140, 260, 311, 81))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.kolor.setFont(font)
        self.kolor.setAutoFillBackground(False)
        self.kolor.setObjectName("kolor")
        self.tlo = QtWidgets.QLabel(Form)
        self.tlo.setGeometry(QtCore.QRect(10, 90, 571, 161))
        self.tlo.setText("")
        self.tlo.setObjectName("tlo")
        self.typtestu = QtWidgets.QLabel(Form)
        self.typtestu.setGeometry(QtCore.QRect(170, 10, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(False)
        font.setWeight(50)
        self.typtestu.setFont(font)
        self.typtestu.setAutoFillBackground(False)
        self.typtestu.setText("")
        self.typtestu.setAlignment(QtCore.Qt.AlignCenter)
        self.typtestu.setObjectName("typtestu")
        self.szybkosc = QtWidgets.QLabel(Form)
        self.szybkosc.setGeometry(QtCore.QRect(460, 260, 111, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.szybkosc.setFont(font)
        self.szybkosc.setAutoFillBackground(False)
        self.szybkosc.setText("")
        self.szybkosc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.szybkosc.setObjectName("szybkosc")
        self.szybkosc.setWordWrap(True)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Test Optyczny"))
        self.informacja.setText(_translate("Form", "Test optyczny. Po kliknięciu 'Dalej' ukaże się okienko z testem. Domyślnie tryb testu ustawiony jest na 'Szkolenie'. Podczas szkolenia wyniki nie będą zapisywane. W celu przejścia do trybu 'Testu' należy kliknąć przycisk w prawym dolnym rogu. W celu uruchomienia badania należy kliknąć 'Start'. Badanie polega na reagowaniu na zmieniający się kolor - kiedy kolor zmieni się z niebieskiego na czerwony, należy kliknąć przycisk 'Kolor'. W celu zobaczenia wszystkich wyników należy przejść do głównego okienka aplikacji i kliknąć przycisk 'Wyświetl wyniki'."))
        self.przycisk.setText(_translate("Form", "Dalej"))
        self.start.setText(_translate("Form", "Start"))
        self.test.setText(_translate("Form", "Test"))
        self.kolor.setText(_translate("Form", "Kolor"))
        self.setWindowIcon(QtGui.QIcon(os.getcwd()+'/data/oko.jpg'))

