from PyQt5 import QtCore, QtGui, QtWidgets
import os

class OpticWindow2(object):
    def setupUi(self, OpticTest2):
        OpticTest2.setObjectName("OpticTest2")
        OpticTest2.resize(586, 443)
        self.informacja = QtWidgets.QLabel(OpticTest2)
        self.informacja.setGeometry(QtCore.QRect(10, 10, 561, 361))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.informacja.setFont(font)
        self.informacja.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.informacja.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.informacja.setWordWrap(True)
        self.informacja.setObjectName("informacja")
        self.przycisk = QtWidgets.QPushButton(OpticTest2)
        self.przycisk.setGeometry(QtCore.QRect(260, 350, 311, 81))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.przycisk.setFont(font)
        self.przycisk.setAutoFillBackground(False)
        self.przycisk.setObjectName("przycisk")
        self.start = QtWidgets.QPushButton(OpticTest2)
        self.start.setEnabled(False)
        self.start.setGeometry(QtCore.QRect(10, 350, 271, 81))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.start.setFont(font)
        self.start.setAutoFillBackground(False)
        self.start.setObjectName("start")
        self.test = QtWidgets.QPushButton(OpticTest2)
        self.test.setEnabled(False)
        self.test.setGeometry(QtCore.QRect(300, 350, 271, 81))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.test.setFont(font)
        self.test.setAutoFillBackground(False)
        self.test.setObjectName("test")
        self.tlo = QtWidgets.QLabel(OpticTest2)
        self.tlo.setGeometry(QtCore.QRect(10, 90, 211, 161))
        self.tlo.setText("")
        self.tlo.setObjectName("tlo")
        self.typtestu = QtWidgets.QLabel(OpticTest2)
        self.typtestu.setEnabled(True)
        self.typtestu.setGeometry(QtCore.QRect(170, 10, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(False)
        font.setWeight(50)
        self.typtestu.setFont(font)
        self.typtestu.setAutoFillBackground(False)
        self.typtestu.setAlignment(QtCore.Qt.AlignCenter)
        self.typtestu.setObjectName("typtestu")
        self.szybkosc = QtWidgets.QLabel(OpticTest2)
        self.szybkosc.setGeometry(QtCore.QRect(140, 60, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.szybkosc.setFont(font)
        self.szybkosc.setAutoFillBackground(False)
        self.szybkosc.setText("")
        self.szybkosc.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.szybkosc.setObjectName("szybkosc")
        self.niebieski1 = QtWidgets.QCheckBox(OpticTest2)
        self.niebieski1.setGeometry(QtCore.QRect(30, 260, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.niebieski1.setFont(font)
        self.niebieski1.setObjectName("niebieski1")
        self.niebieski2 = QtWidgets.QCheckBox(OpticTest2)
        self.niebieski2.setGeometry(QtCore.QRect(240, 260, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.niebieski2.setFont(font)
        self.niebieski2.setObjectName("niebieski2")
        self.niebieski3 = QtWidgets.QCheckBox(OpticTest2)
        self.niebieski3.setGeometry(QtCore.QRect(450, 260, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.niebieski3.setFont(font)
        self.niebieski3.setObjectName("niebieski3")
        self.czerwony1 = QtWidgets.QCheckBox(OpticTest2)
        self.czerwony1.setGeometry(QtCore.QRect(30, 290, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.czerwony1.setFont(font)
        self.czerwony1.setObjectName("czerwony1")
        self.czerwony2 = QtWidgets.QCheckBox(OpticTest2)
        self.czerwony2.setGeometry(QtCore.QRect(240, 290, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.czerwony2.setFont(font)
        self.czerwony2.setObjectName("czerwony2")
        self.czerwony3 = QtWidgets.QCheckBox(OpticTest2)
        self.czerwony3.setGeometry(QtCore.QRect(450, 290, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.czerwony3.setFont(font)
        self.czerwony3.setObjectName("czerwony3")
        self.zolty1 = QtWidgets.QCheckBox(OpticTest2)
        self.zolty1.setGeometry(QtCore.QRect(30, 320, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.zolty1.setFont(font)
        self.zolty1.setObjectName("zolty")
        self.zolty2 = QtWidgets.QCheckBox(OpticTest2)
        self.zolty2.setGeometry(QtCore.QRect(240, 320, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.zolty2.setFont(font)
        self.zolty2.setObjectName("zolty_2")
        self.zolty3 = QtWidgets.QCheckBox(OpticTest2)
        self.zolty3.setGeometry(QtCore.QRect(450, 320, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.zolty3.setFont(font)
        self.zolty3.setObjectName("zolty_3")
        self.tlo2 = QtWidgets.QLabel(OpticTest2)
        self.tlo2.setGeometry(QtCore.QRect(220, 90, 161, 161))
        self.tlo2.setText("")
        self.tlo2.setObjectName("tlo2")
        self.tlo3 = QtWidgets.QLabel(OpticTest2)
        self.tlo3.setGeometry(QtCore.QRect(380, 90, 201, 161))
        self.tlo3.setText("")
        self.tlo3.setObjectName("tlo3")

        self.typtestu.hide()
        self.start.hide()
        self.test.hide()

        self.czerwony1.hide()
        self.czerwony1.setEnabled(False)
        self.czerwony2.hide()
        self.czerwony2.setEnabled(False)
        self.czerwony3.hide()
        self.czerwony3.setEnabled(False)

        self.niebieski1.hide()
        self.niebieski1.setEnabled(False)
        self.niebieski2.hide()
        self.niebieski2.setEnabled(False)        
        self.niebieski3.hide()
        self.niebieski3.setEnabled(False)

        self.zolty1.hide()
        self.zolty1.setEnabled(False)
        self.zolty2.hide()
        self.zolty2.setEnabled(False)
        self.zolty3.hide()
        self.zolty3.setEnabled(False)

        self.retranslateUi(OpticTest2)
        QtCore.QMetaObject.connectSlotsByName(OpticTest2)

    def retranslateUi(self, OpticTest2):
        _translate = QtCore.QCoreApplication.translate
        OpticTest2.setWindowTitle(_translate("OpticTest2", "Test Optyczny Złożony"))
        self.informacja.setText(_translate("OpticTest2", "Test optyczny złożony. Po kliknięciu 'Dalej' ukaże się okienko z badaniem. Domyślnie tryb badania ustawione jest na 'Szkolenie'. Podczas szkolenia wyniki nie będą zapisywane. W celu przejścia do trybu 'Testu' należy kliknąć przycisk w prawym dolnym rogu. W celu uruchomienia badania należy kliknąć 'Start'. Badanie polega na reagowaniu na trzy kolory - niebieski, żółty i czerwony. Tło będzie zmieniać kolory, celem użytkownika jest w jak najkrótszym czasie zaznaczyć odpowiednie kolory w polach pod nimi. W celu zobaczenia wszystkich wyników należy przejść do głównego okienka aplikacji i kliknąć przycisk 'Wyświetl wyniki'."))
        self.przycisk.setText(_translate("OpticTest2", "Dalej"))
        self.start.setText(_translate("OpticTest2", "Start"))
        self.test.setText(_translate("OpticTest2", "Test"))
        self.typtestu.setText(_translate("OpticTest2", "Szkolenie"))
        self.niebieski1.setText(_translate("OpticTest2", "Niebieski"))
        self.niebieski2.setText(_translate("OpticTest2", "Niebieski"))
        self.niebieski3.setText(_translate("OpticTest2", "Niebieski"))
        self.czerwony1.setText(_translate("OpticTest2", "Czerwony"))
        self.czerwony2.setText(_translate("OpticTest2", "Czerwony"))
        self.czerwony3.setText(_translate("OpticTest2", "Czerwony"))
        self.zolty1.setText(_translate("OpticTest2", "Żółty"))
        self.zolty2.setText(_translate("OpticTest2", "Żółty"))
        self.zolty3.setText(_translate("OpticTest2", "Żółty"))
        self.setWindowIcon(QtGui.QIcon(os.getcwd()+'/data/oko.jpg'))
