"""Script containing dicts that we use in ocr text detection"""
from data.Artifacts import *
from data.creature_banks import *
from data.resources import *
from data.all_cities import *
from data.habitats_on_map import *

towns = ["Castle", "Conflux", "Dungeon", "Fortress", "Inferno", "Necropolis", "Rampart", "Stronghold", "Tower", "Cove"]
towns_obj = [Castle(), Conflux(), Dungeon(), Fortress(), Inferno(), Necropolis(), Rampart(), Stronghold(), Tower(),
             Cove()]
resource = ["Gold", "Wood", "Ore", "Mercury", "Sulfur", "Crystal", "Gems"]
resource_obj = [Gold, Wood, Ore, Mercury, Sulfur, Crystal, Gems]
amount = ["Few", "Several", "Pack", "Lots", "Horde", "Throng", "Swarm", "Zounds", "Legion"]
creatures = ["Air Elemental", " Ancient Behemoth", " Angel", " Archangel", " Archer",
             "Arch Devil", " Arch Mage", " Ayssid", " Azure Dragon", " Basilisk",
             "Battle Dwarf", " Behemoth", " Beholder", " Black Dragon", " Black Knight", " Boar",
             "Bone Dragon", " Cavalier", " Centaur", " Centaur Captain", " Cerberus",
             "Champion", " Chaos Hydra", " Corsair", " Crew Mate", " Crusader", " Crystal Dragon",
             "Cyclops", " Cyclops King", " Demon", " Dendroid Guard", " Dendroid Soldier", " Devil",
             "Diamond Golem", " Dragon Fly", " Dread Knight", " Dwarf", " Earth Elemental", " Efreeti",
             "Efreet Sultan", " Enchanter", " Energy Elemental", " Evil Eye", " Faerie Dragon",
             "Familiar", " Fangarm", " Firebird", " Fire Elemental",
             "Genie", " Ghost Dragon", " Giant", " Gnoll", " Gnoll Marauder", " Goblin", " Gog",
             "Gold Dragon", " Gold Golem", " Gorgon", " Grand Elf", " Greater Basilisk",
             "Green Dragon", " Gremlin", " Griffin", " Halberdier", " Halfling", " Harpy",
             "Harpy Hag", " Haspid", " Hell Hound", " Hobgoblin", " Horned Demon", " Hydra",
             "Ice Elemental", " Imp", " Infernal Troglodyte", " Iron Golem", " Leprechaun", " Lich",
             "Lizardman", " Lizard Warrior", " Mage", " Magic Elemental", " Magma Elemental", " Magog",
             "Manticore", " Marksman", " Master Genie", " Master Gremlin", " Medusa", " Medusa Queen",
             "Mighty Gorgon", " Minotaur", " Minotaur King", " Monk", " Mummy", " Naga", " Naga Queen",
             "Nix", " Nix Warrior", " Nomad", " Nymph", " Obsidian Gargoyle", " Oceanid",
             "Ogre", " Ogre Mage", " Orc", " Orc Chieftain", " Peasant", " Pegasus", " Phoenix",
             "Pikeman", " Pirate", " Pit Fiend", " Pit Lord", " Pixie", " Power Lich",
             "Psychic Elemental", " Red Dragon", " Roc", " Rogue", " Royal Griffin",
             "Rust Dragon", " Satyr", " Scorpicore", " Seaman", " Sea Dog", " Sea Serpent",
             "Sea Witch", " Serpent Fly", " Sharpshooter", " Silver Pegasus", " Skeleton",
             "Skeleton Warrior", " Sorceress", " Sprite", " Steel Golem", " Stone Gargoyle",
             "Stone Golem", " Stormbird", " Storm Elemental", " Swordsman", " Thunderbird",
             "Titan", " Troglodyte", " Troll", " Unicorn", " Vampire", " Vampire Lord",
             "Walking Dead", " War Unicorn", " Water Elemental", " Wight", " Wolf Raider",
             "Wolf Rider", " Wood Elf", " Wraith", " Wyvern", " Wyvern Monarch", " Zealot",
             "Zombie"]

creatures_obj = [Air_Elemental, Ancient_Behemoth, Angel, Archangel, Archer,
                 Arch_Devil, Arch_Mage, Ayssid, Azure_Dragon, Basilisk,
                 Battle_Dwarf, Behemoth, Beholder, Black_Dragon, Black_Knight, Boar,
                 Bone_Dragon, Cavalier, Centaur, Centaur_Captain, Cerberus,
                 Champion, Chaos_Hydra, Corsair, Crew_Mate, Crusader, Crystal_Dragon,
                 Cyclops, Cyclops_King, Demon, Dendroid_Guard, Dendroid_Soldier, Devil,
                 Diamond_Golem, Dragon_Fly, Dread_Knight, Dwarf, Earth_Elemental, Efreeti,
                 Efreet_Sultan, Enchanter, Energy_Elemental, Evil_Eye, Faerie_Dragon,
                 Familiar, Fangarm, Firebird, Fire_Elemental,
                 Genie, Ghost_Dragon, Giant, Gnoll, Gnoll_Marauder, Goblin, Gog,
                 Gold_Dragon, Gold_Golem, Gorgon, Grand_Elf, Greater_Basilisk,
                 Green_Dragon, Gremlin, Griffin, Halberdier, Halfling, Harpy,
                 Harpy_Hag, Haspid, Hell_Hound, Hobgoblin, Horned_Demon, Hydra,
                 Ice_Elemental, Imp, Infernal_Troglodyte, Iron_Golem, Leprechaun, Lich,
                 Lizardman, Lizard_Warrior, Mage, Magic_Elemental, Magma_Elemental, Magog,
                 Manticore, Marksman, Master_Genie, Master_Gremlin, Medusa, Medusa_Queen,
                 Mighty_Gorgon, Minotaur, Minotaur_King, Monk, Mummy, Naga, Naga_Queen,
                 Nix, Nix_Warrior, Nomad, Nymph, Obsidian_Gargoyle, Oceanid,
                 Ogre, Ogre_Mage, Orc, Orc_Chieftain, Peasant, Pegasus, Phoenix,
                 Pikeman, Pirate, Pit_Fiend, Pit_Lord, Pixie, Power_Lich,
                 Psychic_Elemental, Red_Dragon, Roc, Rogue, Royal_Griffin,
                 Rust_Dragon, Satyr, Scorpicore, Seaman, Sea_Dog, Sea_Serpent,
                 Sea_Witch, Serpent_Fly, Sharpshooter, Silver_Pegasus, Skeleton,
                 Skeleton_Warrior, Sorceress, Sprite, Steel_Golem, Stone_Gargoyle,
                 Stone_Golem, Stormbird, Storm_Elemental, Swordsman, Thunderbird,
                 Titan, Troglodyte, Troll, Unicorn, Vampire, Vampire_Lord,
                 Walking_Dead, War_Unicorn, Water_Elemental, Wight, Wolf_Raider,
                 Wolf_Rider, Wood_Elf, Wraith, Wyvern, Wyvern_Monarch, Zealot,
                 Zombie]
habitats_obj = [Guardhouse_on_Map, Archers_Tower_on_Map, Griffin_Tower_on_Map, Barracks_on_Map, Monastery_on_Map,
                Training_Grounds_on_Map, Portal_of_Glory_on_Map, Centaur_Stables_on_Map, Dwarf_Cottage_on_Map,
                Homestead_on_Map, Enchanted_Spring_on_Map, Dendroid_Arches_on_Map, Unicorn_Glade_on_Map,
                Dragon_Cliffs_on_Map, Workshop_on_Map, Parapet_on_Map, Golem_Factory_on_Map, Mage_Tower_on_Map,
                Altar_of_Wishes_on_Map, Golden_Pavilion_on_Map, Cloud_Temple_on_Map, Imp_Crucible_on_Map,
                Hall_of_Sins_on_Map, Kennels_on_Map, Demon_Gate_on_Map, Hell_Hole_on_Map, Fire_Lake_on_Map,
                Forsaken_Palace_on_Map, Cursed_Temple_on_Map, Graveyard_on_Map, Tomb_of_Souls_on_Map, Estate_on_Map,
                Mausoleum_on_Map, Hall_of_Darkness_on_Map, Dragon_Vault_on_Map, Warren_on_Map, Harpy_Loft_on_Map,
                Pillar_of_Eyes_on_Map, Chapel_of_Stilled_Voices_on_Map, Labyrinth_on_Map, Manticore_Lair_on_Map,
                Dragon_Cave_on_Map, Goblin_Barracks_on_Map, Wolf_Pen_on_Map, Orc_Tower_on_Map, Ogre_Fort_on_Map,
                Cliff_Nest_on_Map, Cyclops_Cave_on_Map, Behemoth_Lair_on_Map, Gnoll_Hut_on_Map, Lizard_Den_on_Map,
                Serpent_Fly_Hive_on_Map, Basilisk_Pit_on_Map, Gorgon_Lair_on_Map, Wyvern_Nest_on_Map,
                Hydra_Pond_on_Map,
                Magic_Lantern_on_Map, Altar_of_Air_on_Map, Air_Elemental_Conflux_on_Map, Altar_of_Water_on_Map,
                Water_Elemental_Conflux_on_Map, Altar_of_Fire_on_Map, Fire_Elemental_Conflux_on_Map,
                Altar_of_Earth_on_Map, Earth_Elemental_Conflux_on_Map, Altar_of_Thought_on_Map, Pyre_on_Map,
                Nymph_Waterfall_on_Map, Shack_on_Map, Frigate_on_Map, Nest_on_Map, Tower_of_the_Seas_on_Map,
                Nix_Fort_on_Map, Maelstrom_on_Map, Hovel, Thatched_Hut, Rogue_Cavern, Alehouse, Boar_Glen,
                Nomad_Tent,
                Tomb_of_Curses, Wineyard, Treetop_Tower, Troll_Bridge, Ziggurat, Enchanters_Hollow, Magic_Forest,
                Sulfurous_Lair, Crystal_Cave, Frozen_Cliffs, Crypt, Cyclops_Stockpile, Derelict_Ship, Dragon_Fly_Hive,
                Dragon_Utopia, Dwarven_Treasury, Griffin_Conservatory, Imp_Cache, Medusa_Stores, Naga_Bank, Shipwreck,
                Beholders_Sanctuary, Black_Tower, Churchyard, Experimental_Shop, Ivory_Tower, Mansion, Pirate_Cavern,
                Red_Tower, Ruins, Spit, Temple_of_the_Sea, Wolf_Raider_Picket]

habitats = ["Guardhouse", "Archers Tower", "Griffin Tower", "Barracks", "Monastery", "Training Grounds",
            "Portal of Glory", "Centaur Stables", "Dwarf Cottage", "Homestead", "Enchanted Spring",
            "Dendroid Arches",
            "Unicorn Glade", "Dragon Cliffs", "Workshop", "Parapet", "Golem Factory", "Mage Tower",
            "Altar of Wishes",
            "Golden Pavilion", "Cloud Temple", "Imp Crucible", "Hall of Sins", "Kennels", "Demon Gate", "Hell Hole",
            "Fire Lake", "Forsaken Palace", "Cursed Temple", "Graveyard", "Tomb of Souls", "Estate", "Mausoleum",
            "Hall of Darkness", "Dragon Vault", "Warren", "Harpy Loft", "Pillar of Eyes",
            "Chapel of Stilled Voices",
            "Labyrinth", "Manticore Lair", "Dragon Cave", "Goblin Barracks", "Wolf Pen", "Orc Tower", "Ogre Fort",
            "Cliff Nest", "Cyclops Cave", "Behemoth Lair", "Gnoll Hut", "Lizard Den", "Serpent Fly Hive",
            "Basilisk Pit", "Gorgon Lair", "Wyvern Nest", "Hydra Pond", "Magic Lantern", "Altar of Air",
            "Altar of Air",
            "Altar of Water", "Altar of Water", "Altar of Fire", "Altar of Fire", "Altar of Earth",
            "Altar of Earth",
            "Altar of Thought", "Pyre", "Nymph Waterfall", "Shack", "Frigate", "Nest", "Tower of the Seas",
            "Nix Fort",
            "Maelstrom", "Hovel", "Thatched Hut", "Rogue Cavern", "Alehouse", "Boar Glen", "Nomad Tent",
            "Tomb of Curses", "Wineyard", "Treetop Tower", "Troll Bridge", "Ziggurat", "Enchanters Hollow",
            "Magic Forest", "Sulfurous Lair", "Crystal Cave", "Frozen Cliffs", "Crypt", "Cyclops Stockpile", "Derelict Ship", "Dragon Fly Hive",
                "Dragon Utopia", "Dwarven Treasury", "Griffin Conservatory", "Imp Cache", "Medusa Stores", "Naga Bank", "Shipwreck",
                "Beholders Sanctuary", "Black Tower", "Churchyard", "Experimental Shop", "Ivory Tower", "Mansion", "Pirate Cavern",
                "Red Tower", "Ruins", "Spit", "Temple of the Sea", "Wolf Raider Picket"]


artifacts_obj = [Cape_of_Conjuring, Dragon_Wing_Tabard, Vampires_Cowl, Surcoat_of_Counterpoise, Ambassadors_Sash,
                 Everflowing_Crystal_Cloak, Recanters_Cloak, Cape_of_Velocity, Angel_Wings,
                 Cloak_of_the_Undead_King,
                 Cape_of_Silence, Diplomats_Cloak, Dragonbone_Greaves, Boots_of_Speed, Dead_Mans_Boots,
                 Boots_of_Polarity, Sandals_of_the_Saint, Boots_of_Levitation, Wayfarers_Boots,
                 Helm_of_the_Alabaster_Unicorn, Skull_Helmet, Helm_of_Chaos, Crown_of_the_Supreme_Magi,
                 Hellstorm_Helmet, Crown_of_Dragontooth, Thunder_Helmet, Sea_Captains_Hat,
                 Helm_of_Heavenly_Enlightenment, Spellbinders_Hat, Admirals_Hat, Crown_of_the_Five_Seas,
                 Shield_of_the_Dwarven_Lords, Shield_of_the_Yawning_Dead, Buckler_of_the_Gnoll_King,
                 Targ_of_the_Rampaging_Ogre, Shield_of_the_Damned, Dragon_Scale_Shield, Lions_Shield_of_Courage,
                 Sentinels_Shield, Shield_of_Naval_Glory, Spell_Scroll, Charm_of_Mana, Talisman_of_Mana,
                 Mystic_Orb_of_Mana, Wizards_Well, Orb_of_Silt, Orb_of_the_Firmament, Orb_of_Driving_Rain,
                 Orb_of_Tempestuous_Fire, Tome_of_Earth, Tome_of_Air, Tome_of_Water, Tome_of_Fire,
                 Sphere_of_Permanence,
                 Orb_of_Inhibition, Orb_of_Vulnerability, Bird_of_Perception, Stoic_Watchman, Emblem_of_Cognizance,
                 Clover_of_Fortune, Ladybird_of_Luck, Cards_of_Prophecy, Hourglass_of_the_Evil_Hour,
                 Glyph_of_Gallantry,
                 Crest_of_Valor, Badge_of_Courage, Spirit_of_Oppression, Spyglass, Speculum, Golden_Bow,
                 Bow_of_Elven_Cherrywood, Bowstring_of_the_Unicorns_Mane, Angel_Feather_Arrows,
                 Bow_of_the_Sharpshooter,
                 Vial_of_Lifeblood, Elixir_of_Life, Endless_Purse_of_Gold, Endless_Bag_of_Gold,
                 Endless_Sack_of_Gold,
                 Inexhaustible_Cart_of_Lumber, Inexhaustible_Cart_of_Ore, Everpouring_Vial_of_Mercury, Cornucopia,
                 Legs_of_Legion, Loins_of_Legion, Torso_of_Legion, Arms_of_Legion, Head_of_Legion, Statue_of_Legion,
                 Shackles_of_War, Vial_of_Dragon_Blood, Golden_Goose, Hideous_Mask, Runes_of_Imminency,
                 Demons_Horseshoe, Shamans_Puppet, Charm_of_Eclipse, Horn_of_the_Abyss, Pendant_of_Dispassion,
                 Pendant_of_Free_Will, Pendant_of_Life, Pendant_of_Death, Pendant_of_Total_Recall,
                 Pendant_of_Holiness,
                 Pendant_of_Second_Sight, Pendant_of_Negativity, Collar_of_Conjuring, Amulet_of_the_Undertaker,
                 Garniture_of_Interference, Statesmans_Medal, Necklace_of_Swiftness, Pendant_of_Courage,
                 Necklace_of_Dragonteeth, Necklace_of_Ocean_Guidance, Celestial_Necklace_of_Bliss,
                 Pendant_of_Downfall,
                 Pendant_of_Reflection, Centaurs_Axe, Blackshard_of_the_Dead_Knight, Greater_Gnolls_Flail,
                 Ogres_Club_of_Havoc, Sword_of_Hellfire, Red_Dragon_Flame_Tongue, Titans_Gladius,
                 Sword_of_Judgement,
                 Titans_Thunder, Angelic_Alliance, Armageddons_Blade, Trident_of_Dominion, Ironfist_of_the_Ogre,
                 Ring_of_Conjuring, Still_Eye_of_the_Dragon, Quiet_Eye_of_the_Dragon, Equestrians_Gloves,
                 Diplomats_Ring, Ring_of_the_Wayfarer, Ring_of_Vitality, Ring_of_Life, Ring_of_Infinite_Gems,
                 Eversmoking_Ring_of_Sulfur, Ring_of_the_Magi, Ring_of_Suppression, Ring_of_Oblivion,
                 Seal_of_Sunset,
                 Breastplate_of_Petrified_Wood, Rib_Cage, Scales_of_the_Greater_Basilisk, Tunic_of_the_Cyclops_King,
                 Breastplate_of_Brimstone, Armor_of_Wonder, Dragon_Scale_Armor, Titans_Cuirass, Armor_of_the_Damned,
                 Power_of_the_Dragon_Father, Royal_Armor_of_Nix, Plate_of_Dying_Light]
artifacts = ["Cape of Conjuring", "Dragon Wing Tabard", "Vampires Cowl", "Surcoat of Counterpoise",
             "Ambassadors Sash",
             "Everflowing Crystal Cloak", "Recanters Cloak", "Cape of Velocity", "Angel Wings",
             "Cloak of the Undead King", "Cape of Silence", "Diplomats Cloak", "Dragonbone Greaves",
             "Boots of Speed",
             "Dead Mans Boots", "Boots of Polarity", "Sandals of the Saint", "Boots of Levitation",
             "Wayfarers Boots",
             "Helm of the Alabaster Unicorn", "Skull Helmet", "Helm of Chaos", "Crown of the Supreme Magi",
             "Hellstorm Helmet", "Crown of Dragontooth", "Thunder Helmet", "Sea Captains Hat",
             "Helm of Heavenly Enlightenment", "Spellbinders Hat", "Admirals Hat", "Crown of the Five Seas",
             "Shield of the Dwarven Lords", "Shield of the Yawning Dead", "Buckler of the Gnoll King",
             "Targ of the Rampaging Ogre", "Shield of the Damned", "Dragon Scale Shield", "Lions Shield of Courage",
             "Sentinels Shield", "Shield of Naval Glory", "Spell Scroll", "Charm of Mana", "Talisman of Mana",
             "Mystic Orb of Mana", "Wizards Well", "Orb of Silt", "Orb of the Firmament", "Orb of Driving Rain",
             "Orb of Tempestuous Fire", "Tome of Earth", "Tome of Air", "Tome of Water", "Tome of Fire",
             "Sphere of Permanence", "Orb of Inhibition", "Orb of Vulnerability", "Bird of Perception",
             "Stoic Watchman", "Emblem of Cognizance", "Clover of Fortune", "Ladybird of Luck", "Cards of Prophecy",
             "Hourglass of the Evil Hour", "Glyph of Gallantry", "Crest of Valor", "Badge of Courage",
             "Spirit of Oppression", "Spyglass", "Speculum", "Golden Bow", "Bow of Elven Cherrywood",
             "Bowstring of the Unicorns Mane", "Angel Feather Arrows", "Bow of the Sharpshooter",
             "Vial of Lifeblood",
             "Elixir of Life", "Endless Purse of Gold", "Endless Bag of Gold", "Endless Sack of Gold",
             "Inexhaustible Cart of Lumber", "Inexhaustible Cart of Ore", "Everpouring Vial of Mercury",
             "Cornucopia",
             "Legs of Legion", "Loins of Legion", "Torso of Legion", "Arms of Legion", "Head of Legion",
             "Statue of Legion", "Shackles of War", "Vial of Dragon Blood", "Golden Goose", "Hideous Mask",
             "Runes of Imminency", "Demons Horseshoe", "Shamans Puppet", "Charm of Eclipse", "Horn of the Abyss",
             "Pendant of Dispassion", "Pendant of Free Will", "Pendant of Life", "Pendant of Death",
             "Pendant of Total Recall", "Pendant of Holiness", "Pendant of Second Sight", "Pendant of Negativity",
             "Collar of Conjuring", "Amulet of the Undertaker", "Garniture of Interference", "Statesmans Medal",
             "Necklace of Swiftness", "Pendant of Courage", "Necklace of Dragonteeth", "Necklace of Ocean Guidance",
             "Celestial Necklace of Bliss", "Pendant of Downfall", "Pendant of Reflection", "Centaurs Axe",
             "Blackshard of the Dead Knight", "Greater Gnolls Flail", "Ogres Club of Havoc", "Sword of Hellfire",
             "Red Dragon Flame Tongue", "Titans Gladius", "Sword of Judgement", "Titans Thunder",
             "Angelic Alliance",
             "Armageddons Blade", "Trident of Dominion", "Ironfist of the Ogre", "Ring of Conjuring",
             "Still Eye of the Dragon", "Quiet Eye of the Dragon", "Equestrians Gloves", "Diplomats Ring",
             "Ring of the Wayfarer", "Ring of Vitality", "Ring of Life", "Ring of Infinite Gems",
             "Eversmoking Ring of Sulfur", "Ring of the Magi", "Ring of Suppression", "Ring of Oblivion",
             "Seal of Sunset", "Breastplate of Petrified Wood", "Rib Cage", "Scales of the Greater Basilisk",
             "Tunic of the Cyclops King", "Breastplate of Brimstone", "Armor of Wonder", "Dragon Scale Armor",
             "Titans Cuirass", "Armor of the Damned", "Power of the Dragon Father", "Royal Armor of Nix",
             "Plate of Dying Light"]
amount_num = [3, 8, 18, 45, 80, 220, 800, 1500]
