name: "Python Check"
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.ACTION_COMMIT }}
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Upgrade pip
      run: pip install --upgrade pip
    - name: install libraries for checks
      run: pip install black==23.9.1 pylint==2.17.7
    - run: black $(git ls-files '*.py')
    - run: pylint --disable=all --enable=unused-import $(git ls-files '*.py')
    
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: github-actions
        author_email: github-actions[bot]@users.noreply.github.com
        message: '[github-actions] Add refactoring changes'
        add: '*.py'
